[[article]]
title = "Canada's Housing Supply Is In Crisis. Can Robots Help?"
publication = "Betakit"
date = "January 2026"
href = "https://betakit.com/canadas-housing-supply-is-in-crisis-can-robots-help"

[[article]]
title = "Is Calgary's Public Transit System Keeping The City From Moving Forward?"
publication = "Avenue Magazine"
date = "March 2023"
href = "https://www.avenuecalgary.com/city-life/is-calgarys-public-transit-system-keeping-the-city-from-moving-forward/"

[[article]]
title = "Opinion: The Queen's Death Is A Reminder Of How Few Women Leaders There Are"
publication = "CBC"
date = "September 2022"
href = "https://www.cbc.ca/news/canada/calgary/opinion-queen-death-women-leaders-feminism-1.6585597"

[[article]]
title = "Why Dating In Calgary Is Such A Crazy Mix Of Energy And Anxiety — Part 1"
publication = "CBC"
date = "February 2019"
href = "https://www.cbc.ca/news/canada/calgary/opinion-why-dating-in-calgary-is-such-a-crazy-mix-of-energy-and-anxiety-1.5012469"

[[article]]
title = "How A Culture Of Coupledom, Some Loneliness, And Just Getting Older Complicates Dating In Calgary — Part 2"
publication = "CBC"
date = "February 2019"
href = "https://www.cbc.ca/news/canada/calgary/opinion-dating-calgary-jessica-barrett-part-2-1.5016665"

[[article]]
title = "I Left Vancouver Because Vancouver Left Me"
publication = "The Tyee"
date = "October 2017"
href = "https://thetyee.ca/Opinion/2017/10/30/I-Left-Vancouver"